import { defineConfig } from "@/lib/config";

// Private clone configuration - generated by setup script
const useCloneBranding = true;

export default defineConfig({
  // Branding - your organization's identity
  branding: {
    name: "WCC Prompts  Library",
    logo: "/WCCLogo.svg",
    logoDark: "/WCCLogoDark.svg",
    favicon: "/WCCLogo.svg",
    description: "Collect, organize, and share AI prompts",
  },

  // Theme - design system configuration
  theme: {
    radius: "sm",
    variant: "default",
    density: "default",
    colors: {
      primary: "#FF4701",
    },
  },

  // Authentication plugins
  auth: {
    providers: ["github"],
    allowRegistration: false,
  },

  // Internationalization
  i18n: {
    locales: ["en"],
    defaultLocale: "en",
  },

  // Features
  features: {
    privatePrompts: true,
    changeRequests: true,
    categories: true,
    tags: true,
    comments: true,
    aiSearch: false,
    aiGeneration: false,
    mcp: true,
  },

  // Homepage customization (clone branding mode)
  homepage: {
    useCloneBranding,
    achievements: {
      enabled: false, // Disabled for private clones
    },
    sponsors: {
      enabled: false,
      items: [],
    },
  },
});
