#!/bin/bash
set -e

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║   🚀 prompts.chat - AI Prompt Library                        ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Paths
APP_DIR="/app"
PGDATA="/data/postgres"
PGBIN="/usr/lib/postgresql/15/bin"
BUILD_MARKER="/data/.built"

# Generate AUTH_SECRET if not provided
if [ -z "$AUTH_SECRET" ]; then
    if [ -f "/data/.auth_secret" ]; then
        export AUTH_SECRET=$(cat /data/.auth_secret)
    else
        export AUTH_SECRET=$(openssl rand -base64 32)
        echo "$AUTH_SECRET" > /data/.auth_secret
        echo "⚠ AUTH_SECRET generated and saved"
    fi
fi

# Set AUTH_URL for OAuth callback URLs
# Without this, NextAuth uses the container's internal address (0.0.0.0:3000)
if [ -n "$PCHAT_URL" ]; then
    export AUTH_URL="$PCHAT_URL"
elif [ -z "$AUTH_URL" ]; then
    export AUTH_URL="http://localhost:${PCHAT_PORT:-4444}"
    echo "⚠ AUTH_URL not set, defaulting to $AUTH_URL"
    echo "  Set PCHAT_URL for OAuth providers (e.g. -e PCHAT_URL=http://localhost:4444)"
fi

# Write runtime env vars for the Next.js process
# supervisord may not reliably pass through all container env vars,
# so we create a startup script that carries the full environment.
cat > /app/start-nextjs.sh << 'SCRIPT'
#!/bin/bash
exec node /app/.next/standalone/server.js
SCRIPT
chmod +x /app/start-nextjs.sh

# Generate env file for Next.js runtime (all relevant env vars)
ENV_FILE="/app/.env.runtime"
echo "# Auto-generated by bootstrap.sh" > "$ENV_FILE"
for var in AUTH_URL AUTH_SECRET DATABASE_URL DIRECT_URL \
           AUTH_GITHUB_ID AUTH_GITHUB_SECRET GITHUB_CLIENT_ID GITHUB_CLIENT_SECRET \
           AUTH_GOOGLE_ID AUTH_GOOGLE_SECRET GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET \
           AUTH_AZURE_AD_CLIENT_ID AUTH_AZURE_AD_CLIENT_SECRET AUTH_AZURE_AD_ISSUER AZURE_AD_CLIENT_ID AZURE_AD_CLIENT_SECRET AZURE_AD_TENANT_ID \
           OPENAI_API_KEY NODE_ENV PORT HOSTNAME; do
    if [ -n "${!var}" ]; then
        echo "export $var=\"${!var}\"" >> "$ENV_FILE"
    fi
done

# Initialize PostgreSQL if needed
if [ ! -f "$PGDATA/PG_VERSION" ]; then
    echo "▶ Initializing PostgreSQL..."
    su postgres -c "$PGBIN/initdb -D $PGDATA"
    
    cat >> "$PGDATA/postgresql.conf" << EOF
listen_addresses = 'localhost'
port = 5432
max_connections = 100
shared_buffers = 128MB
EOF
    
    cat > "$PGDATA/pg_hba.conf" << EOF
local all all trust
host all all 127.0.0.1/32 trust
host all all ::1/128 trust
EOF
    
    su postgres -c "$PGBIN/pg_ctl -D $PGDATA -l /tmp/pg.log start"
    sleep 3
    su postgres -c "$PGBIN/createuser -s prompts 2>/dev/null" || true
    su postgres -c "$PGBIN/createdb -O prompts prompts 2>/dev/null" || true
    su postgres -c "$PGBIN/pg_ctl -D $PGDATA stop"
    sleep 2
    echo "✓ PostgreSQL initialized"
fi

# Build on first run (source code is already in /app from Docker image)
if [ ! -f "$BUILD_MARKER" ]; then
    echo ""
    echo "▶ First run detected - building prompts.chat..."
    echo ""

    cd "$APP_DIR"

    # Generate config from environment variables
    echo "▶ Generating configuration..."
    
    # Map PCHAT_* env vars to what docker-setup.js expects
    export BRAND_NAME="${PCHAT_NAME:-$BRAND_NAME}"
    export BRAND_DESCRIPTION="${PCHAT_DESCRIPTION:-$BRAND_DESCRIPTION}"
    export BRAND_LOGO="${PCHAT_LOGO:-$BRAND_LOGO}"
    export BRAND_LOGO_DARK="${PCHAT_LOGO_DARK:-$BRAND_LOGO_DARK}"
    export BRAND_FAVICON="${PCHAT_FAVICON:-$BRAND_FAVICON}"
    export BRAND_COLOR="${PCHAT_COLOR:-$BRAND_COLOR}"
    export THEME_RADIUS="${PCHAT_THEME_RADIUS:-$THEME_RADIUS}"
    export THEME_VARIANT="${PCHAT_THEME_VARIANT:-$THEME_VARIANT}"
    export THEME_DENSITY="${PCHAT_THEME_DENSITY:-$THEME_DENSITY}"
    export AUTH_PROVIDERS="${PCHAT_AUTH_PROVIDERS:-$AUTH_PROVIDERS}"
    export ALLOW_REGISTRATION="${PCHAT_ALLOW_REGISTRATION:-$ALLOW_REGISTRATION}"
    export LOCALES="${PCHAT_LOCALES:-$LOCALES}"
    export DEFAULT_LOCALE="${PCHAT_DEFAULT_LOCALE:-$DEFAULT_LOCALE}"
    export FEATURE_PRIVATE_PROMPTS="${PCHAT_FEATURE_PRIVATE_PROMPTS:-$FEATURE_PRIVATE_PROMPTS}"
    export FEATURE_CHANGE_REQUESTS="${PCHAT_FEATURE_CHANGE_REQUESTS:-$FEATURE_CHANGE_REQUESTS}"
    export FEATURE_CATEGORIES="${PCHAT_FEATURE_CATEGORIES:-$FEATURE_CATEGORIES}"
    export FEATURE_TAGS="${PCHAT_FEATURE_TAGS:-$FEATURE_TAGS}"
    export FEATURE_COMMENTS="${PCHAT_FEATURE_COMMENTS:-$FEATURE_COMMENTS}"
    export FEATURE_AI_SEARCH="${PCHAT_FEATURE_AI_SEARCH:-$FEATURE_AI_SEARCH}"
    export FEATURE_AI_GENERATION="${PCHAT_FEATURE_AI_GENERATION:-$FEATURE_AI_GENERATION}"
    export FEATURE_MCP="${PCHAT_FEATURE_MCP:-$FEATURE_MCP}"
    
    node scripts/docker-setup.js
    echo "✓ Configuration generated"

    # Generate Prisma client
    echo "▶ Generating Prisma client..."
    npx prisma generate
    echo "✓ Prisma client generated"

    # Build Next.js
    echo "▶ Building Next.js application (this may take a few minutes)..."
    npm run build
    echo "✓ Build complete"

    # Copy static files for standalone mode
    echo "▶ Copying static assets..."
    cp -r .next/static .next/standalone/.next/
    cp -r public .next/standalone/
    echo "✓ Static assets copied"

    # Mark as built
    touch "$BUILD_MARKER"

    echo ""
    echo "✅ Build complete! Starting application..."
    echo ""
else
    echo "✓ Using existing build"
    cd "$APP_DIR"
fi

# Start supervisord (manages PostgreSQL and Next.js)
echo "▶ Starting services..."
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf &
SUPERVISOR_PID=$!

# Wait for PostgreSQL
echo "▶ Waiting for PostgreSQL..."
for i in $(seq 1 30); do
    if $PGBIN/pg_isready -h localhost -p 5432 >/dev/null 2>&1; then
        echo "✓ PostgreSQL is ready"
        break
    fi
    if [ $i -eq 30 ]; then
        echo "✗ PostgreSQL failed to start"
        exit 1
    fi
    sleep 1
done

# Run migrations
echo "▶ Running database migrations..."
cd "$APP_DIR"
npx prisma migrate deploy
echo "✓ Migrations complete"

# Seed on first run only
SEED_MARKER="/data/.seeded"
if [ ! -f "$SEED_MARKER" ]; then
    echo "▶ Seeding database..."
    if npx tsx prisma/seed.ts 2>/dev/null; then
        touch "$SEED_MARKER"
        echo "✓ Database seeded"
    else
        echo "⚠ Seeding skipped"
    fi
fi

# Wait for supervisord socket to be ready
echo "▶ Waiting for supervisord..."
for i in $(seq 1 30); do
    if supervisorctl -c /etc/supervisor/conf.d/supervisord.conf pid >/dev/null 2>&1; then
        echo "✓ Supervisord is ready"
        break
    fi
    if [ $i -eq 30 ]; then
        echo "✗ Supervisord failed to start"
        exit 1
    fi
    sleep 1
done

# Start Next.js
echo "▶ Starting Next.js..."
supervisorctl -c /etc/supervisor/conf.d/supervisord.conf start nextjs

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║   ✅ prompts.chat is running!                                 ║"
echo "║                                                               ║"
echo "║   🌐 Open http://localhost:${PORT:-3000} in your browser         ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

wait $SUPERVISOR_PID
